### ISSUE TITLE
Website link not working

### ISSUE THREAD

**Issue by Pi-thagoras** [anonymoof1528/the-shadow-garten#1]
Please push right now so that i can see this amazing masterpiece in action.

![istockphoto-94462256-612x612](https://github.com/anonymoof1528/the-shadow-garten/assets/85726663/4f5e5167-2c29-4390-b129-42ec574c2bf3)

**Comment by spicata** [comment]
Please give me administrator perms

**Comment by Pi-thagoras** [comment]
![image](https://github.com/anonymoof1528/the-shadow-garten/assets/85726663/277b98c3-125e-42ee-b236-5f5e9cd928ac)

**Comment by anonymoof1528** [comment]
I CANT PUSH I'M SPEC'ING

________________________________

**Comment by anonymoof1528** [comment]
and why wings

**Comment by anonymoof1528** [comment]
it's not even live yet
so problem solved
made spic a collaborator hopefully he can change things then
